#!/usr/bin/env bash
# https://github.com/harvesthq/api/blob/master/Sections/Time%20and%20Expense%20Reporting.md

curl -s -H 'Content-Type: application/json' -H 'Accept: application/json'  \
    -u $HVSTEMAIL:$HVSTPASSWORD  \
    "https://connerweb.harvestapp.com/people/$1/entries?from=$2&to=$3"
