#!/usr/bin/env bash
# https://github.com/harvesthq/api/blob/master/Sections/People.md

curl -s -H 'Content-Type: application/json' -H 'Accept: application/json'  \
    -u $HVSTEMAIL:$HVSTPASSWORD  \
    "https://connerweb.harvestapp.com/people"
